name: fraud_shield
description: A Flutter application to protect businesses from courier fraud.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/banner.jpg